apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-push-image-pipeline-binding
spec:
  params:
    - name: dockerfile-path
      value: "./Dockerfile"
    - name: image-url
      value: "docker.io/ruqaiya009/tekton-img"
    - name: path-to-context
      value: "workspace/shared-data"


---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-push-image-template
  namespace: default
spec:
  params:
  - name: dockerfile-path
    description: dockerfile-path.
  - name: image-url
    description: image-url.
  - name: path-to-context
    description: path-to-context.
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-build-push-image-$(uid)
        namespace: default
      spec:
        serviceAccountName: git-serviceaccount
        pipelineRef:
          name: pipeline-build-push-image
        resources:
          - name: input-git
            resourceRef:
              name: go-api-skeleton-git
          - name: output-image
            resourceRef:
              name: go-api-skeleton-image
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        params:
          - name: dockerfile-path
            value: "./Dockerfile"
          - name: image-url
            value: "docker.io/ruqaiya009/tekton-img"
          - name: path-to-context
            value: "workspace/shared-data" 

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-push-image-tekton-trigger-listener
spec:
  serviceAccountName: service-tekton-triggers-sa
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - pull_request
              - push
      bindings:
        - ref: build-push-image-pipeline-binding
      template:
        ref: build-push-image-template

---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  annotations:
    tekton.dev/git-0: github.com # Described below
type: Opaque
stringData:
  secretToken: "yossi"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-tekton-triggers-sa  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-example-minimal
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
# configmaps is needed for updating logging config
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["tekton-triggers"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-example-binding
subjects:
- kind: ServiceAccount
  name: service-tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-example-minimal
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-example-clusterrole
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings", "clusterinterceptors"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-example-clusterbinding
subjects:
- kind: ServiceAccount
  name: service-tekton-triggers-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-example-clusterrole
   